language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - oraclejdk11
before_install:
  # ensure gradlew has proper permission
  - chmod a+x ./gradlew
script:
- echo "skipping tests"
#  - gradle test