/*
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * GetAddressUtxosResponseInner
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-01T23:18:44.045Z")
public class GetAddressUtxosResponseInner {
  @SerializedName("address")
  private String address = null;

  @SerializedName("txid")
  private String txid = null;

  @SerializedName("vout")
  private BigDecimal vout = null;

  @SerializedName("ts")
  private BigDecimal ts = null;

  @SerializedName("scriptPubKey")
  private String scriptPubKey = null;

  @SerializedName("amount")
  private BigDecimal amount = null;

  @SerializedName("confirmations")
  private BigDecimal confirmations = null;

  public GetAddressUtxosResponseInner address(String address) {
    this.address = address;
    return this;
  }

   /**
   * Address
   * @return address
  **/
  @ApiModelProperty(value = "Address")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public GetAddressUtxosResponseInner txid(String txid) {
    this.txid = txid;
    return this;
  }

   /**
   * Transaction ID
   * @return txid
  **/
  @ApiModelProperty(value = "Transaction ID")
  public String getTxid() {
    return txid;
  }

  public void setTxid(String txid) {
    this.txid = txid;
  }

  public GetAddressUtxosResponseInner vout(BigDecimal vout) {
    this.vout = vout;
    return this;
  }

   /**
   * vout
   * @return vout
  **/
  @ApiModelProperty(value = "vout")
  public BigDecimal getVout() {
    return vout;
  }

  public void setVout(BigDecimal vout) {
    this.vout = vout;
  }

  public GetAddressUtxosResponseInner ts(BigDecimal ts) {
    this.ts = ts;
    return this;
  }

   /**
   * Timestamp
   * @return ts
  **/
  @ApiModelProperty(value = "Timestamp")
  public BigDecimal getTs() {
    return ts;
  }

  public void setTs(BigDecimal ts) {
    this.ts = ts;
  }

  public GetAddressUtxosResponseInner scriptPubKey(String scriptPubKey) {
    this.scriptPubKey = scriptPubKey;
    return this;
  }

   /**
   * scriptPubKey
   * @return scriptPubKey
  **/
  @ApiModelProperty(value = "scriptPubKey")
  public String getScriptPubKey() {
    return scriptPubKey;
  }

  public void setScriptPubKey(String scriptPubKey) {
    this.scriptPubKey = scriptPubKey;
  }

  public GetAddressUtxosResponseInner amount(BigDecimal amount) {
    this.amount = amount;
    return this;
  }

   /**
   * NEBL amount
   * @return amount
  **/
  @ApiModelProperty(value = "NEBL amount")
  public BigDecimal getAmount() {
    return amount;
  }

  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }

  public GetAddressUtxosResponseInner confirmations(BigDecimal confirmations) {
    this.confirmations = confirmations;
    return this;
  }

   /**
   * Number of confirmations
   * @return confirmations
  **/
  @ApiModelProperty(value = "Number of confirmations")
  public BigDecimal getConfirmations() {
    return confirmations;
  }

  public void setConfirmations(BigDecimal confirmations) {
    this.confirmations = confirmations;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetAddressUtxosResponseInner getAddressUtxosResponseInner = (GetAddressUtxosResponseInner) o;
    return Objects.equals(this.address, getAddressUtxosResponseInner.address) &&
        Objects.equals(this.txid, getAddressUtxosResponseInner.txid) &&
        Objects.equals(this.vout, getAddressUtxosResponseInner.vout) &&
        Objects.equals(this.ts, getAddressUtxosResponseInner.ts) &&
        Objects.equals(this.scriptPubKey, getAddressUtxosResponseInner.scriptPubKey) &&
        Objects.equals(this.amount, getAddressUtxosResponseInner.amount) &&
        Objects.equals(this.confirmations, getAddressUtxosResponseInner.confirmations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, txid, vout, ts, scriptPubKey, amount, confirmations);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetAddressUtxosResponseInner {\n");
    
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    txid: ").append(toIndentedString(txid)).append("\n");
    sb.append("    vout: ").append(toIndentedString(vout)).append("\n");
    sb.append("    ts: ").append(toIndentedString(ts)).append("\n");
    sb.append("    scriptPubKey: ").append(toIndentedString(scriptPubKey)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    confirmations: ").append(toIndentedString(confirmations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

