/*
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * GetRawTxResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-01T23:18:44.045Z")
public class GetRawTxResponse {
  @SerializedName("rawtx")
  private String rawtx = null;

  public GetRawTxResponse rawtx(String rawtx) {
    this.rawtx = rawtx;
    return this;
  }

   /**
   * Raw hex representing the transaction
   * @return rawtx
  **/
  @ApiModelProperty(value = "Raw hex representing the transaction")
  public String getRawtx() {
    return rawtx;
  }

  public void setRawtx(String rawtx) {
    this.rawtx = rawtx;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetRawTxResponse getRawTxResponse = (GetRawTxResponse) o;
    return Objects.equals(this.rawtx, getRawTxResponse.rawtx);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rawtx);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetRawTxResponse {\n");
    
    sb.append("    rawtx: ").append(toIndentedString(rawtx)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

