/*
 * Neblio REST API Suite
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * IssueTokenRequestMetadataRulesHolders
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-20T00:20:46.329Z")
public class IssueTokenRequestMetadataRulesHolders {
  @SerializedName("address")
  private String address = null;

  @SerializedName("locked")
  private Boolean locked = null;

  public IssueTokenRequestMetadataRulesHolders address(String address) {
    this.address = address;
    return this;
  }

   /**
   * Address that can hold the token
   * @return address
  **/
  @ApiModelProperty(value = "Address that can hold the token")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public IssueTokenRequestMetadataRulesHolders locked(Boolean locked) {
    this.locked = locked;
    return this;
  }

   /**
   * Whether this rule can be modified in future transactions
   * @return locked
  **/
  @ApiModelProperty(value = "Whether this rule can be modified in future transactions")
  public Boolean isLocked() {
    return locked;
  }

  public void setLocked(Boolean locked) {
    this.locked = locked;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IssueTokenRequestMetadataRulesHolders issueTokenRequestMetadataRulesHolders = (IssueTokenRequestMetadataRulesHolders) o;
    return Objects.equals(this.address, issueTokenRequestMetadataRulesHolders.address) &&
        Objects.equals(this.locked, issueTokenRequestMetadataRulesHolders.locked);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, locked);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IssueTokenRequestMetadataRulesHolders {\n");
    
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    locked: ").append(toIndentedString(locked)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

